export const language = {
	account: `Account`,
	atomicAsset: `Atomic Asset`,
	appName: `BazAR`,
	blockHeight: `Block Height`,
	buyNow: `Buy Now`,
	close: `Close`,
	connect: `Connect`,
	copied: `Copied`,
	copyAddress: `Copy Address`,
	dateCreated: `Date Created`,
	details: `Details`,
	disconnect: `Disconnect`,
	fetching: `Fetching`,
	listing: `Listing`,
	loading: `Loading`,
	noAssets: `No Assets`,
	overview: `Overview`,
	owners: `Owners`,
	pageNotFound: `Page Not Found`,
	provenanceDetails: `Provenance Details`,
	standard: `Standard`,
	stampCount: `STAMPs`,
	transactionId: `Transaction ID`,
	walletNotConnected: `Connect a wallet to continue`,
};
