export const language = {
	address: `Address`,
	arweaveAppConnectionError: `Connection error with Arweave.app. The connector window must remain open after the initial connection.`,
	assetNotTradeable: `This asset is not tradeable`,
	assets: 'Atomic Assets',
	account: `View Profile`,
	activity: `Activity`,
	activeListings: `Active Listings`,
	activeNode: `Selected`,
	activeSaleOrders: `Active Sale Orders`,
	atomicAsset: `Atomic Asset`,
	appName: `BazAR`,
	approximateStreakTime: `You have approximately`,
	approximateStreakTimeInfo: `Until you can continue building your streak`,
	approximateStreakTimeRemaining: `Buy an asset in this window to build your Streak and increase your $PIXL rewards`,
	arProfileCreate: `To create your AR Profile, click here:`,
	assetHasBeenBurned: `This asset has been burned`,
	assetPercentage: `Asset Percentage`,
	assetPercentageInfo: `Slide For Percentage of Asset`,
	assetQuantity: `Asset Quantity`,
	assetQuantityInfo: `Slide For Quantity of Asset`,
	assetRights: `Asset Rights`,
	assetStamped: `Asset Stamped`,
	amountExceedsBalance: `Amount exceeds Balance`,
	blockHeight: `Block Height`,
	burnYourOwn: `Burn your own`,
	buy: `Buy`,
	buyOnEverPay: `Buy on everPay`,
	buyNow: `Buy Now`,
	byStamps: `By Stamps`,
	cancel: `Cancel`,
	cancelOrder: `Cancel Order`,
	cancelOrderConfirmation: `Confirm Order Cancellation`,
	cancelOrderConfirmationInfo: `This will remove the active listing that you have created on this asset. Users will no longer see this order in the active orders list.`,
	cannotCancelOrder: `Unable to cancel this order`,
	chart: `Chart`,
	close: `Close`,
	collection: `Collection`,
	collections: `Collections`,
	collectionStamped: `Collection Stamped`,
	comment: `Comment`,
	comments: `Comments`,
	commentStamped: `Comment Stamped`,
	confirm: `Confirm`,
	confirmListing: `Confirm Listing`,
	confirmPayment: `Confirm Payment`,
	confirmPurchase: `Confirm Purchase`,
	confirmTransfer: `Confirm Transfer`,
	connect: `Connect`,
	connectorNotFound: `This connector was not found`,
	connectWalletToComment: `Connect a wallet to comment`,
	connectWalletToStamp: `Connect a wallet to STAMP`,
	connectedDisabledSale: `You must be the owner of this asset to list it for sale`,
	contentTypeNotSupported: `Content Type Not Supported`,
	connectedDisabledTransfer: `You must be the owner of this asset to transfer it`,
	copied: `Copied`,
	copyAddress: `Copy Address`,
	copyURL: `Copy URL`,
	createProfile: `Create Profile`,
	createdBy: `Created by`,
	currencyBalanceWarning: `Not enough balance to purchase this asset`,
	currentOwners: `Current Owners`,
	currentAssetOwners: `Current Asset Owners`,
	currentlyBeingSoldBy: `Currently being sold by`,
	currentlyOwnedBy: `Currently owned by`,
	dataProtocol: `Data Protocol`,
	dateCreated: `Date Created`,
	dayCount: (count: number) => `${count} Day${count > 1 ? 's' : ''}`,
	dayStreak: (length: string) => `${length} day streak`,
	details: `Details`,
	disconnect: `Disconnect`,
	errorFetchingAsset: `Error Fetching Asset`,
	errorOccurred: `Error Occurred`,
	fetching: `Fetching`,
	floorPrice: `Floor Price`,
	getU: `Get U`,
	goBack: `Go Back`,
	grid: `Grid`,
	highToLow: `Highest to Lowest`,
	invalidAddress: `Invalid Address`,
	learn: `Learn`,
	leaveComment: `Leave a comment`,
	license: `License`,
	licensePaid: `License Paid`,
	licenseText: `License Text`,
	listing: `Listing`,
	listNow: `List Now`,
	listPrice: `List Price`,
	listingSuccess: `Listing Successful`,
	load: `Load`,
	loading: `Loading`,
	loadAssetData: `Load Asset Data`,
	lowToHigh: `Lowest to Highest`,
	market: `Market`,
	max: `Max`,
	microscope: `Microscope`,
	myAssets: `My Assets`,
	new: `New`,
	next: `Next`,
	noAssets: `No Assets`,
	noCollections: `No Collections`,
	noListings: `No Listings`,
	none: `None`,
	orderBook: `Order Book`,
	orderCancelled: `Order Cancelled`,
	orderPendingDescription: `Your order is pending and will resolve shortly, you may close this window.`,
	other: `Other`,
	overview: `Overview`,
	owner: `owner`,
	owners: `owners`,
	pageNotFound: `Page Not Found`,
	pasteFromClipboard: `Paste From Clipboard`,
	payLicense: `Pay License`,
	pending: `Pending`,
	percentage: `Percentage`,
	previous: `Previous`,
	protocolName: `Protocol Name`,
	provenanceDetails: `Provenance Details`,
	purchaseSuccess: `Purchase Successful`,
	quantity: `Quantity`,
	quantityAboveZero: `Quantity must be above 0`,
	quantityExceedsBalance: `Quantity exceeds max available balance`,
	quantityMustBeInteger: `Quantity must be an integer`,
	rank: `Rank`,
	recipientAddress: `Recipient Address`,
	relatedTransactions: `Related Transactions`,
	reply: `Reply`,
	replied: `Replied`,
	rootNode: `Current`,
	saleQuantityTooltip: `This value represents the total quantity of the asset you currently own that you would like to list for sale`,
	saleTotalPriceTooltip: `This value represents the total price of the asset you want to list it for`,
	saleUnitPriceTooltip: `This value represents the cost for 1 unit of the asset in U`,
	searchAssets: `Search Assets`,
	selectDRENode: `Select DRE Node`,
	sell: `Sell`,
	seller: `Seller`,
	sellAsset: `Sell Asset`,
	settings: `Settings`,
	shareOn: `Share on`,
	shareProfile: `Share Profile`,
	social: {
		twitter: `Twitter`,
	},
	showMore: `Show More`,
	standard: `Standard`,
	stamp: `STAMP`,
	stamps: `Stamps`,
	stampComment: `STAMP Comment`,
	stampCount: `STAMPs`,
	stampInfo: `STAMP if you like this content, STAMPs generate rewards for the creators of an Atomic Asset, Super STAMP if you want tip some of your STAMP rewards to the Atomic Asset Sponsors.`,
	stampsVouched: `Vouched STAMPs`,
	streak: `Streak`,
	streakInfo: `UCM tracks buying streaks, which occur when users buy one or more Atomic Assets on consecutive days.<br><br><b>A streak boosts the user's share for daily rewards. The longer your streak, the more $PIXL you can earn.</b>`,
	streakInfoDetails: `See Full Profile`,
	streakLeaderboard: `Streak Leaderboard`,
	streakStart: `Buy an asset today to start your streak`,
	streakTitle1: `Start your streak`,
	streakTitle2: `Getting warmer`,
	streakTitle3: `Building the flame`,
	streakTitle4: `Rising heat`,
	streakTitle5: `You're on fire`,
	submit: `Submit`,
	superStamp: `Super STAMP`,
	swap: `Swap`,
	total: `Total`,
	totalAssetBalance: `Total Asset Balance`,
	totalBuyPercentage: `Total Buy Percentage`,
	totalBuyQuantity: `Total Buy Quantity`,
	totalListingPercentage: `Total Listing Percentage`,
	totalListingQuantity: `Total Listing Quantity`,
	totalPrice: `Total Price`,
	totalSalesBalance: `Total Balance For Sale`,
	totalAvailableSalesBalance: `Total Balance Available For Sale`,
	totalAvailableTransferBalance: `Total Balance Available For Transfer`,
	totalSalesPercentage: `Total Percentage For Sale`,
	totalTransferPercentage: `Total Transfer Percentage`,
	totalTransferQuantity: `Total Transfer Quantity`,
	totalAvailableSalesPercentage: `Total Percentage Available For Sale`,
	totalAvailableTransferPercentage: `Total Percentage Available For Transfer`,
	transaction: `Transaction`,
	transactionId: `Transaction ID`,
	transfer: `Transfer`,
	transferPendingDescription: `Your transfer is pending and will resolve shortly, you may close this window.`,
	uDescription: `$U is the native currency of the permaweb. $U creates a fast and efficient user experience for the permaweb with a focus on permanence and verification. Get $U by burning or swapping $AR here.`,
	unitPrice: `Unit Price`,
	unitPriceAboveDecimal: `Unit price must be above 0.000001`,
	unitPriceAboveZero: `Unit price must be above 0`,
	unitPriceBelowDecimal: `Unit price must have at most 6 decimal places`,
	updatingAsset: `Updating Asset`,
	totalPriceAboveZero: `Unit price must be above 0`,
	viewAllCollections: `View All Collections`,
	viewblock: `Viewblock`,
	viewDetails: `View Details`,
	viewCollection: `View Collection`,
	viewUCM: `Buy / Sell $PIXL`,
	walletNotConnected: `Connect a wallet to continue`,
	walletTransactionInfo: `Your wallet must be connected to make transactions`,
	weeklyAssetActivity: `Past Week Asset Activity`,
	yourPixlBalane: `Your $PIXL Balance`,
	yourStreak: `Your Streak`,
	yourUCMOwnershipPercentage: `Your UCM Ownership Percentage`,
};
