export const language = {
	account: `Account`,
	activeSaleOrders: `Active Sale Orders`,
	atomicAsset: `Atomic Asset`,
	appName: `BazAR`,
	arProfileCreate: `To create your AR Profile, click here:`,
	assetPercentageInfo: `Slide For Percentage of Asset`,
	blockHeight: `Block Height`,
	buy: `Buy`,
	buyNow: `Buy Now`,
	close: `Close`,
	confirmListing: `Confirm Listing`,
	confirmPurchase: `Confirm Purchase`,
	connect: `Connect`,
	copied: `Copied`,
	copyAddress: `Copy Address`,
	createProfile: `Create Profile`,
	currentAssetOwners: `Current Asset Owners`,
	dateCreated: `Date Created`,
	details: `Details`,
	disconnect: `Disconnect`,
	fetching: `Fetching`,
	listing: `Listing`,
	listNow: `List Now`,
	listingSuccess: `Listing Successful`,
	loading: `Loading`,
	max: `Max`,
	myAssets: `My Assets`,
	next: `Next`,
	noAssets: `No Assets`,
	none: `None`,
	overview: `Overview`,
	owners: `Owners`,
	pageNotFound: `Page Not Found`,
	previous: `Previous`,
	provenanceDetails: `Provenance Details`,
	purchaseSuccess: `Purchase Successful`,
	quantity: `Quantity`,
	search: `Search`,
	sell: `Sell`,
	sellAsset: `Sell Asset`,
	standard: `Standard`,
	stampCount: `STAMPs`,
	submit: `Submit`,
	totalAssetBalance: `Total Asset Balance`,
	totalBuyPercentage: `Total Buy Percentage`,
	totalBuyQuantity: `Total Buy Quantity`,
	totalListingPercentage: `Total Listing Percentage`,
	totalListingQuantity: `Total Listing Quantity`,
	totalPrice: `Total Price`,
	totalSalesBalance: `Total Balance For Sale`,
	totalAvailableSalesBalance: `Total Balance Available For Sale`,
	totalSalesPercentage: `Total Percentage For Sale`,
	totalAvailableSalesPercentage: `Total Percentage Available For Sale`,
	transactionId: `Transaction ID`,
	unitPrice: `Unit Price`,
	walletNotConnected: `Connect a wallet to continue`,
};
